### PR TITLE
Mm-branch

### PR DESCRIPTION
**Pull request by MsTDMc**
Added Notebooks us_crime_rates_1960_2014 
crime_unemployment_inflation

### CODE REVIEW

**Review by kkruel8100 — COMMENTED** [review]
Main no longer will open.  I'm going to try to pull out the changes into another branch.

**Review by kkruel8100 — CHANGES_REQUESTED** [review]
Main no longer opens/runs.  I'm going to try and pull out the changes in a separate branch.

**Comment by kkruel8100** [comment]
I was able to pull in the changes to a local branch and commit/push your changes.  I listed mm on the commit for your name.  The commit has all the work you completed.

Screenshot 2024-02-10 at 8 59 29 PM

**Comment by col-mustang** [comment]
changes pushed in separate branch by Kim

**Pull request closed without merging**
